version: "3.7"
services:
    gateway:
        build:
            context: gateway/docker
            dockerfile: development/nginx/Dockerfile
        ports:
            - "8080:8080"
    app:
        build:
            context: app/docker
            dockerfile: development/nginx/Dockerfile
        volumes:
            - ./app:/app

    app-php-fpm:
        build:
            context: app/docker
            dockerfile: development/php-fpm/Dockerfile
        volumes:
            - ./app:/app
        environment:
            APP_DEBUG: 1
            APP_ENV: dev
            PHP_IDE_CONFIG: serverName=API

    app-php-cli:
        build:
            context: app/docker
            dockerfile: development/php-cli/Dockerfile
        volumes:
            - ./app:/app
        environment:
            APP_DEBUG: 1
            APP_ENV: dev
